#pragma once

#define NAMESIZE 256

#define SCREENWIDTH 320
#define SCREENHEIGHT 240

#define GRAVITY 0.1
#define AIRRESISTANCE 0.99

#define ENEMYMAX 16
#define TILEMAX 16
#define DRAWINGMAX 16
#define PHYSICSMAX 16

#define NUMSCANCODES 284
#define CONTROLLERSIZE 32 // 2 axes, 14 buttons = 16; x2 for future-proofing.
#define CONTROLLERMAX 16
#define INPUTSPACE (NUMSCANCODES + CONTROLLERSIZE * CONTROLLERMAX)
